# Generated by Django 4.2.1 on 2023-08-14 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0001_initial'),
        ('step_types', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classiclesson',
            name='stage',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='lms.stage'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='stage',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='lms.stage'),
        ),
    ]
