# Generated by Django 4.2.1 on 2023-08-15 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0001_initial'),
        ('step_types', '0003_remove_classiclesson_id_remove_classiclesson_stage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classiclesson',
            name='lessontype_ptr',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='lessontype_ptr',
        ),
        migrations.AddField(
            model_name='classiclesson',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='classiclesson',
            name='lesson_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='classic_lesson_type', to='step_types.lessontype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quiz',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quiz',
            name='lesson_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='quiz_lesson_type', to='step_types.lessontype'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lessontype',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_lesson', to='lms.stage'),
        ),
    ]
