# Generated by Django 4.2.1 on 2023-08-15 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0001_initial'),
        ('step_types', '0004_remove_classiclesson_lessontype_ptr_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classiclesson',
            name='id',
        ),
        migrations.RemoveField(
            model_name='classiclesson',
            name='lesson_type',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='id',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='lesson_type',
        ),
        migrations.AddField(
            model_name='classiclesson',
            name='lessontype_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='step_types.lessontype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quiz',
            name='lessontype_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='step_types.lessontype'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lessontype',
            name='stage',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='type_lesson', to='lms.stage'),
        ),
    ]
