# Generated by Django 4.2.1 on 2023-08-27 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('step_types', '0006_classiclesson_is_classic_quiz_answer2_quiz_answer3_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('lessontype_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='step_types.lessontype')),
                ('is_video', models.BooleanField(default=True)),
                ('video_lesson', models.URLField()),
                ('description', models.CharField(max_length=150)),
            ],
            bases=('step_types.lessontype',),
        ),
    ]
