# Generated by Django 4.2.1 on 2023-08-14 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('student_image', models.ImageField(null=True, upload_to='student_profile_images/')),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(blank=True, max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('interested_categories', models.TextField()),
                ('verify_status', models.BooleanField(default=False)),
                ('otp_digit', models.CharField(max_length=10, null=True)),
            ],
            options={
                'verbose_name': 'ученик',
                'verbose_name_plural': 'ученики',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('teacher_image', models.ImageField(null=True, upload_to='teacher_profile_images/')),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(blank=True, max_length=100)),
                ('qualification', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('skills', models.TextField()),
                ('verify_status', models.BooleanField(default=False)),
                ('otp_digit', models.CharField(max_length=10, null=True)),
            ],
            options={
                'verbose_name': 'учитель',
                'verbose_name_plural': 'учителя',
            },
        ),
    ]
