# Generated by Django 4.2.1 on 2023-06-06 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_teacher_detail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='phone',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='student',
            name='address',
        ),
        migrations.RemoveField(
            model_name='student',
            name='qualification',
        ),
    ]
